### Auth sign up
POST {{API_HOST}}/auth/signup HTTP/1.1
content-type: application/json

{
    "first_name":"Scott",
    "last_name":"William",
    "mobile_phone_prefix":"+91",
    "mobile_no":"9612494749",
    "birth":"2020-12-12",
    "gender":"M",
    "password":"Mango"
}

### Auth sign in
POST {{API_HOST}}/auth/login HTTP/1.1
content-type: application/json

{
    "email":"sachin@gmail.com",
    "password":"mango"
}

### Get authenticated user
GET {{API_HOST}}/auth/me HTTP/1.1


### Logout user
GET {{API_HOST}}/auth/logout HTTP/1.1

### Auth Login
POST {{API_HOST}}/auth/login HTTP/1.1
content-type: application/json

{
    "mobile_prefix":"+91",
    "mobile_phone":"9612494749",
    "password":"Mango"
}

### Auth Send OTP
POST {{API_HOST}}/auth/sendotp HTTP/1.1
content-type: application/json

{
    "mobile_phone":"+916909210880"
}

### Auth Send OTP
POST {{API_HOST}}/auth/verifyotp HTTP/1.1
content-type: application/json

{
    "code":"123456",
    "session_key":"AHTqx5YEjuQkcaxKc3Ox_n9suqOm2L6tSCPKmwKSoaa0kpLvvM_QmC4Bx_F6f6wz2UDKqODVs7GyDatNL0mDpTDL55bjDXcw3w_huwqYIsU6udL2YM6bHP3tEzbVcSBf3a3p2XWd3t-aE2mOh4aMGAu8YO-svmN-jg"
}