
GET {{API_HOST}}/permission/count
Authorization: Bearer {{API_KEY}}

### Get all users
GET {{API_HOST}}/permission
Authorization: Bearer {{API_KEY}}

### Get a user by id
GET {{API_HOST}}/permission/1
Authorization: Bearer {{API_KEY}}

### Create a user
POST {{API_HOST}}/permission
content-type: application/json
Authorization: Bearer {{API_KEY}}

{
    "name": "create",
    "description": "To create new",
    "status": 1
}

### Update a user
PATCH {{API_HOST}}/permission/1
content-type: application/json
Authorization: Bearer {{API_KEY}}

{
    "name": "create-new",
    "description": "To create new-update",
    "status": 0
}

### Delete a user by id
DELETE {{API_HOST}}/permission/1
content-type: application/json
Authorization: Bearer {{API_KEY}}
