
GET {{API_HOST}}/role/count
Authorization: Bearer {{API_KEY}}

### Get all users
GET {{API_HOST}}/role
Authorization: Bearer {{API_KEY}}

### Get a user by id
GET {{API_HOST}}/role/1
Authorization: Bearer {{API_KEY}}

### Create a user
POST {{API_HOST}}/role
content-type: application/json
Authorization: Bearer {{API_KEY}}

{
    "name": "Doctor",
    "description": "Dcotor",
    "status": 1
}

### Update a user
PATCH {{API_HOST}}/role/1
content-type: application/json
Authorization: Bearer {{API_KEY}}

{
    "name": "LinkedDoctor",
    "description": "To create new-update",
    "status": 0
}

### Delete a user by id
DELETE {{API_HOST}}/role/1
content-type: application/json
Authorization: Bearer {{API_KEY}}
